# Dependencies
markdown:         kramdown
#highlighter:      pygments


# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Peter Bonventre
tagline:          'Peter Bonventre'
description:      'Mathematician, Postdoctoral Scholar, University of Kentucky'
url:              https://www.ms.uky.edu/~pjbo227/index.html
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

#paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
