# Setup
title:            Peter Bonventre
tagline:          'Peter Bonventre'
description:      Assistant Teaching Professor, <br> Mathematics, <br> Georgetown University
url:              https://petejb88.github.io
baseurl:          ''
paginate:         5
future:           true

author:           
  name:           'Peter Bonventre'

github:
  repo:           https://github.com/petejb88

# Gems
plugins:
        - jekyll-paginate
        - jekyll-gist
        
