# Setup
title:            Peter Bonventre
tagline:          'Peter Bonventre'
description:      'Mathematician, Postdoctoral Scholar, University of Kentucky'
url:              https://petejb88.github.io
baseurl:          ''
paginate:         5

author:           
  name:           'Peter Bonventre'

github:
  repo:           https://github.com/petejb88

# Gems
plugins:
        - jekyll-paginate
        - jekyll-gist
        
