# Dependencies
markdown:         redcarpet
#highlighter:      pygments


# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Peter Bonventre
tagline:          'Peter Bonventre'
description:      'Graduate Student and Ph.D. Candidate at University of Virginia'
url:              http://people.virginia.edu/~pjb9ub/home.html
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

#paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
